[xmpp]
jid = "example@example.com"
password = "your-password"
ssl_verify = false

[xmpp.subscribes]
auto_approve = true

[xmpp.iq.version]
name = "mcabber"
version = "1.1.2"
# os = "TempleOS"

[openai]
enabled = false
api_key = "your-api-key"
model = "gpt-3.5-turbo"
user_nick = "bot"
system_nick = "instructor"
max_tokens = 4096
tokens_reserved_for_response = 512
timezone = "America/New_York"

# Instruct your AI here
# [openai.prelude]
# text = """
# You are helpful assistant.
# """
#
# [[openai.prelude.example]]
# role = "user"
# content = "What is XMPP?"
#
# [[openai.prelude.example]]
# role = "assistant"
# content = "XMPP is extensible messaging protocol"

[webui]
listen = 'localhost'
port = 8000
debug = true
# passwords_sha512 = ["", ""]
websocket_endpoint = "ws://localhost:8000/ws"

# Auth cookie will be signed with this key
# signing_key = ""

# Period after auth cookie will expire
# Format: <number>s/m/h/d/w (seconds, minutes, hours, days, weeks)
# Set to empty string to disable expiration
auth_expiration = "1w"

[xmpp.rooms.test]
join = true
jid = "test@conference.example.com"
nick = "bot"

[database]
path = "./history.db"

[logging]
version = 1

[logging.formatters.default]
format = "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"

[logging.handlers.default]
class = "logging.StreamHandler"
formatter = "default"
level = "INFO"
stream = "ext://sys.stdout"

[logging.handlers.debugging]
class = "logging.StreamHandler"
formatter = "default"
level = "DEBUG"
stream = "ext://sys.stdout"

[logging.loggers.'']
handlers = ["default"]
level = "INFO"
propagate = false

[logging.loggers.aioxmpp]
handlers = ["debugging"]
level = "DEBUG"
propagate = false