-- +goose Up
CREATE SCHEMA IF NOT EXISTS chat;

CREATE TABLE chat.chats (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jid    text    NOT NULL UNIQUE,
    name   text    NOT NULL,
    is_muc boolean NOT NULL
);

CREATE TABLE chat.messages (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id  bigint      NOT NULL REFERENCES chat.chats (id),
    ts       timestamptz NOT NULL,
    kind     smallint    NOT NULL,
    nick     text        NOT NULL,
    text     text        NOT NULL DEFAULT '',
    outgoing boolean     NOT NULL DEFAULT false,
    -- id of the bus event the message was created from, makes redelivery idempotent
    event_id uuid UNIQUE
);

-- Used by the dates skip-scan and by per-day message queries.
CREATE INDEX messages_chat_ts ON chat.messages (chat_id, ts);

CREATE TABLE chat.nick_colors (
    nick  text PRIMARY KEY,
    color text NOT NULL
);

-- Import data from the Python (Pony ORM) version when its tables exist.
-- Old tables are left untouched.
-- +goose StatementBegin
-- message.utctime is "timestamp" (naive UTC) in databases created by Pony
-- and "timestamptz" in some migrated ones; both are handled.
DO $$
DECLARE
    ts_expr text;
BEGIN
    IF to_regclass('public.message') IS NOT NULL AND to_regclass('public.chat') IS NOT NULL THEN
        INSERT INTO chat.chats (id, jid, name, is_muc)
        SELECT id, jid, name, is_muc FROM public.chat;

        ts_expr := CASE
            WHEN (SELECT data_type FROM information_schema.columns
                  WHERE table_schema = 'public' AND table_name = 'message' AND column_name = 'utctime')
                 = 'timestamp with time zone'
            THEN 'utctime'
            ELSE $q$utctime AT TIME ZONE 'UTC'$q$
        END;

        EXECUTE format($q$
            INSERT INTO chat.messages (id, chat_id, ts, kind, nick, text, outgoing)
            SELECT id, chat, %s, msg_type, nick, coalesce(text, ''), outgoing
            FROM public.message$q$, ts_expr);
    END IF;

    IF to_regclass('public.nickcolor') IS NOT NULL THEN
        INSERT INTO chat.nick_colors (nick, color)
        SELECT nick, color FROM public.nickcolor
        ON CONFLICT DO NOTHING;
    END IF;
END
$$;
-- +goose StatementEnd

SELECT setval(pg_get_serial_sequence('chat.chats', 'id'), coalesce(max(id), 0) + 1, false) FROM chat.chats;
SELECT setval(pg_get_serial_sequence('chat.messages', 'id'), coalesce(max(id), 0) + 1, false) FROM chat.messages;

-- +goose Down
DROP SCHEMA chat CASCADE;
